plugins {
    id 'application'
    id 'net.benelog.spidersense'
}

spiderSense {
    port = 4003
}

dependencies {
    spiderSense project(path: ':spider-sense-agent', configuration: 'senseJar')

    implementation "com.zaxxer:HikariCP:${hikariVersion}"
    implementation "com.h2database:h2:${h2Version}"
    implementation "ch.qos.logback:logback-classic:${logbackVersion}"
    implementation "io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations:${otelAgentVersion}"

    testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
    testImplementation "org.assertj:assertj-core:${assertjVersion}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'worker.WorkerApp'

    applicationDefaultJvmArgs = [
            '-Dotel.service.name=batch-worker',
            '-Xmx256m'
    ]
}
