-- The bookstore schema, and what is deliberately missing from it.
--
-- There is no index on books.title, books.description or books.author, and
-- that is the point: "where lower(title) like '%...%'" then scans every one of
-- the 200,000 seeded rows, which is the slow query Spider Sense is meant to
-- show. Only the primary keys and reviews.book_id are indexed, so the fast
-- endpoints stay fast and the difference is visible.

create table if not exists authors (
    id   bigint generated by default as identity primary key,
    name varchar(200) not null
);

create table if not exists books (
    id             bigint generated by default as identity primary key,
    isbn           varchar(20)    not null,
    title          varchar(300)   not null,
    author         varchar(200)   not null,
    price          decimal(10, 2) not null,
    published_year int            not null,
    description    varchar(2000)  not null
);

create table if not exists reviews (
    id         bigint generated by default as identity primary key,
    book_id    bigint        not null,
    author_id  bigint        not null,
    rating     int           not null,
    body       varchar(1000) not null,
    created_at timestamp     not null
);

create index if not exists reviews_book_idx on reviews (book_id);
