plugins {
    id 'application'
    id 'net.benelog.spidersense'
}

spiderSense {
    port = 4002
}

dependencies {
    spiderSense project(path: ':spider-sense-agent', configuration: 'senseJar')

    implementation "org.apache.tomcat.embed:tomcat-embed-core:${rootProject.ext.tomcatVersion}"
    implementation "org.apache.tomcat:tomcat-jdbc:${rootProject.ext.tomcatVersion}"
    implementation "com.h2database:h2:${rootProject.ext.h2Version}"

    testImplementation "org.junit.jupiter:junit-jupiter:${rootProject.ext.junitVersion}"
    testImplementation "org.assertj:assertj-core:${rootProject.ext.assertjVersion}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'warehouse.WarehouseApp'

    applicationDefaultJvmArgs = [
            '-Dotel.service.name=servlet-warehouse'
    ]
}
